// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:ipo/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFs2o2QGpsqi4IhEzc2v20ZUUW6E6c-A',
    appId: '1:1095715911554:web:69db7c14e258f6bac6419b',
    messagingSenderId: '1095715911554',
    projectId: 'iposetu',
    authDomain: 'iposetu.firebaseapp.com',
    storageBucket: 'iposetu.firebasestorage.app',
    measurementId: 'G-EVFMH34NHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4CfETf14Q_hudEOrFDFUUs2ZuMBQB1I',
    appId: '1:1095715911554:android:fa8c6805e8685192c6419b',
    messagingSenderId: '1095715911554',
    projectId: 'iposetu',
    storageBucket: 'iposetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xDJQKg60dByWQRzRtevP18l5QS5aJgQ',
    appId: '1:1095715911554:ios:698826143e96b524c6419b',
    messagingSenderId: '1095715911554',
    projectId: 'iposetu',
    storageBucket: 'iposetu.firebasestorage.app',
    iosBundleId: 'com.example.ipo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xDJQKg60dByWQRzRtevP18l5QS5aJgQ',
    appId: '1:1095715911554:ios:698826143e96b524c6419b',
    messagingSenderId: '1095715911554',
    projectId: 'iposetu',
    storageBucket: 'iposetu.firebasestorage.app',
    iosBundleId: 'com.example.ipo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARFs2o2QGpsqi4IhEzc2v20ZUUW6E6c-A',
    appId: '1:1095715911554:web:424e2449f0a02c75c6419b',
    messagingSenderId: '1095715911554',
    projectId: 'iposetu',
    authDomain: 'iposetu.firebaseapp.com',
    storageBucket: 'iposetu.firebasestorage.app',
    measurementId: 'G-L62NJTVHB6',
  );
}
